# Generated by Django 4.1.7 on 2023-02-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputtrain',
            name='net',
        ),
        migrations.RemoveField(
            model_name='lif',
            name='net',
        ),
        migrations.AddField(
            model_name='abstractnode',
            name='net',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='editor.network'),
        ),
    ]
